namespace KmsReportClient.Model.Enums
{
    public enum ConsolidateReport
    {
        Consolidate262T1,
        Consolidate262T2,
        Consolidate262T3,
        ConsolidateFilial294,
        ConsolidateFull294,
        ControlZpzMonthly,
        ControlZpzQuarterly,
        ZpzWebSite,
        Onko,
        OnkoQuarterly,
        CnpnQuarterly,
        CnpnMonthly,
        Cardio,
        Disp,
        Letal,
        ConsolidateOped,
        ConsolidateVSS,
        ConsolidateOpedQ,
        Proposal,
        ConsolidateCPNP2Q,
        ConsOpedFinance1,
        ConsOpedFinance2,
        ConsPropsal,
    }
}
